import Head from "next/head";
import { Button, Typography, styled } from "@mui/material";

export default function Home() {
  const BlueButton = styled(Button)({
    background: "skyblue",
    color: "pink",
    ml: 1,
    ":hover": { background: "red" },
    transition: "1s",
    ":disabled": { background: "yellow" },
  });

  return (
    <>
      <Head>
        <title>Simple MUI project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button variant="contained" size="large">
          Contained
        </Button>
        <Typography variant="h6" component="p">
          h1. Heading
        </Typography>
        <Button
          variant="contained"
          sx={{
            background: "skyblue",
            color: "pink",
            ml: 1,
            ":hover": { background: "red" },
            transition: "1s",
            ":disabled": { background: "yellow" },
          }}
        >
          Button with sx prop
        </Button>
        <BlueButton>Elo?</BlueButton>
      </main>
    </>
  );
}
